// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBfSNC1B-uc-clQS65akwGtaxnzcn7DuwQ',
    appId: '1:196557612032:web:d0f795279fa15e5ac824e5',
    messagingSenderId: '196557612032',
    projectId: 'upcominggamesapp',
    authDomain: 'upcominggamesapp.firebaseapp.com',
    storageBucket: 'upcominggamesapp.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBUOeYvgbGwdfwD9SqiTMepM_4Q2mbM14w',
    appId: '1:196557612032:android:59acd5c16a661e51c824e5',
    messagingSenderId: '196557612032',
    projectId: 'upcominggamesapp',
    storageBucket: 'upcominggamesapp.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB7caxil_br22f2g27xKYemgGxD5uyfYBA',
    appId: '1:196557612032:ios:1121538777b3f0adc824e5',
    messagingSenderId: '196557612032',
    projectId: 'upcominggamesapp',
    storageBucket: 'upcominggamesapp.appspot.com',
    iosBundleId: 'com.example.upcomingGames',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB7caxil_br22f2g27xKYemgGxD5uyfYBA',
    appId: '1:196557612032:ios:1121538777b3f0adc824e5',
    messagingSenderId: '196557612032',
    projectId: 'upcominggamesapp',
    storageBucket: 'upcominggamesapp.appspot.com',
    iosBundleId: 'com.example.upcomingGames',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBfSNC1B-uc-clQS65akwGtaxnzcn7DuwQ',
    appId: '1:196557612032:web:c938b44af51572d9c824e5',
    messagingSenderId: '196557612032',
    projectId: 'upcominggamesapp',
    authDomain: 'upcominggamesapp.firebaseapp.com',
    storageBucket: 'upcominggamesapp.appspot.com',
  );

}